import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'
import Nav from './_fragments/Nav';
import Header from './_fragments/Header';
import Footer from './_fragments/footer/Footer';
import Counsel from './_fragments/Counsel';

export const metadata: Metadata = {
  title: '엣지이동식주택',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'font-pretendard'}>
        <Header>
          <Nav />
        </Header>
        <main className="flex flex-col min-h-screen h-fit gap-16">
          {children}
        </main>
        <Footer />
        <Counsel />
      </body>
    </html>
  )
}
