import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'
import Nav from './_fragments/Nav';
import Header from './_fragments/Header';

const notoKr = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '엣지이동식주택',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notoKr.className}>
        <Header>
          <Nav />
        </Header>
        {children}
      </body>
    </html>
  )
}
